#user creation header columns(lowercase it all)
EMAIL_HEADER = 'email'
FIRST_NAME_HEADER = 'first name'
LAST_NAME_HEADER = 'last name'
JOB_HEADER = 'job title'
DEPARTMENT_HEADER = 'department'
PHONE_HEADER = 'phone number'
LOCATION_HEADER = 'location'
LOCALE_HEADER = 'locale'
MANAGER_HEADER = 'manager email'
CREATION_HEADERS = [EMAIL_HEADER, FIRST_NAME_HEADER, LAST_NAME_HEADER, JOB_HEADER, DEPARTMENT_HEADER, PHONE_HEADER, LOCATION_HEADER, LOCALE_HEADER, MANAGER_HEADER]
DELETION_HEADERS = [EMAIL_HEADER]
UPDATE_HEADERS = [EMAIL_HEADER, FIRST_NAME_HEADER, LAST_NAME_HEADER, JOB_HEADER, DEPARTMENT_HEADER, PHONE_HEADER, LOCATION_HEADER, LOCALE_HEADER, MANAGER_HEADER]
