# Copyright 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
#
#user creation header columns(lowercase it all)
EMAIL_HEADER = 'email'
FIRST_NAME_HEADER = 'first name'
LAST_NAME_HEADER = 'last name'
JOB_HEADER = 'job title'
DEPARTMENT_HEADER = 'department'
PHONE_HEADER = 'phone number'
LOCATION_HEADER = 'location'
LOCALE_HEADER = 'locale'
MANAGER_HEADER = 'manager email'
TIMEZONE_HEADER = 'timezone'
EXTERNALID_HEADER = 'external id'
ORGANIZATION_HEADER = 'organization'
DIVISION_HEADER = 'division'
COSTCENTER_HEADER = 'cost center'
STARTDATE_HEADER = 'start date'


CREATE_UPDATE_REQUIRED_HEADERS = [EMAIL_HEADER, FIRST_NAME_HEADER, LAST_NAME_HEADER, JOB_HEADER, DEPARTMENT_HEADER, PHONE_HEADER, LOCATION_HEADER, LOCALE_HEADER, MANAGER_HEADER]
DELETION_HEADERS = [EMAIL_HEADER]
CREATE_UPDATE_EXPECTED_HEADERS = [EMAIL_HEADER, FIRST_NAME_HEADER, LAST_NAME_HEADER, JOB_HEADER, DEPARTMENT_HEADER, PHONE_HEADER, LOCATION_HEADER, LOCALE_HEADER, MANAGER_HEADER, TIMEZONE_HEADER, EXTERNALID_HEADER, ORGANIZATION_HEADER, DIVISION_HEADER, COSTCENTER_HEADER, STARTDATE_HEADER]